include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_relative_lib_imports: true
    avoid_returning_this: true
    avoid_return_types_on_setters: true
    avoid_null_checks_in_equality_operators: true
    avoid_multiple_declarations_per_line: true
    avoid_empty_else: true
    avoid_catches_without_on_clauses: true
    avoid_as: true
    always_require_non_null_named_parameters: true
    always_put_required_named_parameters_first: true
    always_put_control_body_on_new_line: true
    always_declare_return_types: true
    always_specify_types: true
    lines_longer_than_80_chars: true
    no_adjacent_strings_in_list: true
    non_constant_identifier_names: true
    sort_pub_dependencies: true
    slash_for_doc_comments: true
    type_annotate_public_apis: true
    unnecessary_const: true
    unnecessary_new: true
    use_key_in_widget_constructors: true
    use_string_buffers: true
    valid_regexps: true
    void_checks: true
    # Performance
    avoid_redundant_argument_values: true
    avoid_web_libraries_in_flutter: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    unrelated_type_equality_checks: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_to_and_as_if_applicable: true